<?php
/**
 * This file generated by Zend\Expressive\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via zend-expressive-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            App\Handler\HelloHandler::class => App\Handler\HelloHandlerFactory::class,
            App\Handler\PhpCommunitiesCreateHandler::class => App\Handler\PhpCommunitiesCreateHandlerFactory::class,
            App\Handler\PhpCommunitiesHandler::class => App\Handler\PhpCommunitiesHandlerFactory::class,
            App\XClacksOverheadMiddleware::class => App\XClacksOverheadMiddlewareFactory::class,
            PhpCommunities\Handler\PhpCommunitiesHandler::class => PhpCommunities\Handler\PhpCommunitiesHandlerFactory::class,
            Series\Handler\GenreHandler::class => Series\Handler\GenreHandlerFactory::class,
        ],
    ],
];
